[package]
authors = ["Jesper Jensen <jesper@slashwin.dk>"]
name = "send"
version = "0.1.0"
build = "build.rs"

[dependencies]
ansi_term = "0.9.0"
byteorder = "1.0.0"
clap = "2.20.0"
libc = "0.2.18"
log = "0.3.6"
pbr = "1.0.0"

[build-dependencies]
byteorder = "1.0.0"
